class Constants:
    kHz = 1e3
    SOURCE_COMMING_CLOSER = -1
    SOURCE_COMMING_FURTHER = 1
    OBSERVER_COMMING_CLOSER = 1
    OBSERVER_COMMING_FURTHER = -1
    SIGNAL_FILENAME = "dsss_m4_B8000_data3_ks5_0_1s.csv"
    ALL_FREQUENCIES_MODE = "ALL"
    CENTER_FREQUENCY_MODE = "CENTER"
    SIGNAL_SOURCE_FROM_FILE = "FILE"
    SIGNAL_SOURCE_GENERATED = "GENERATED"
    BROADEN_SIGNAL_PLOT_T_LENGTH = 3
    INTERP_SAMPLE_NUMBER_INCREASE = 10