
class Constants:
    # przeniesc zmienne gdzies indziej i zostawic ttlko stale
    TEMPERATURE = 10
    kHz = 1e3
    F0 = 1
    FMAX = 100*kHz
    # cz. probkowania
    SAMPLING_RATE = 96*kHz
    DT = 1/SAMPLING_RATE 
    SIGNAL_DURATION = 0.1
    SAMPLES_NUMBER = SIGNAL_DURATION*SAMPLING_RATE
    NUMBER_OF_COMPONENTS = 10
    OBSERVER_VELOCITY = 50
    SOURCE_VELOCITY = 0
    SOURCE_COMMING_CLOSER = -1
    SOURCE_COMMING_FURTHER = 1
    OBSERVER_COMMING_CLOSER = 1
    OBSERVER_COMMING_FURTHER = -1
    ANGLE_BETWEEN_V_VECTOR_AND_WAVE_VECTOR = 30
    SIGNAL_FILENAME = "dsss_m4_B8000_data3_ks5_0_1s.csv"
    CENTER_FREQUENCY = 30*kHz
    ALL_FREQUENCIES_MODE = "ALL"
    CENTER_FREQUENCY_MODE = "CENTER"
    SIGNAL_SOURCE_FROM_FILE = "FILE"
    SIGNAL_SOURCE_GENERATED = "GENERATED"