class Constants:
    kHz = 1e3
    OBSERVER_COMMING_CLOSER = 1
    OBSERVER_COMMING_FURTHER = -1
    SIGNAL_FILENAME = "dsss_m4_B8000_data3_ks5_0_1s.csv"
    SIGNAL_SOURCE_FROM_FILE = "From file"
    SIGNAL_SOURCE_GENERATED = "Generated"
    BROADEN_SIGNAL_PLOT_T_LENGTH = 1.5
    INTERP_SAMPLE_NUMBER_INCREASE = 10
    TIME_DOMAIN = "Time domain"
    FREQUENCY_DOMAIN = "Frequency domain"
